"""File classification and property detection for repository inventory."""

from __future__ import annotations

import re
from pathlib import Path

from codeatlas.core import detect_language
from codeatlas.repository.models import RepositoryFile

_BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".ico", ".webp", ".svgz",
    ".pdf", ".zip", ".tar", ".gz", ".tgz", ".bz2", ".xz", ".7z",
    ".pyc", ".pyo", ".pyd", ".exe", ".dll", ".so", ".dylib",
    ".woff", ".woff2", ".ttf", ".eot", ".otf",
    ".mp3", ".mp4", ".mov", ".avi", ".wav", ".flac",
    ".bin", ".dat", ".db", ".sqlite", ".sqlite3",
}

_GENERATED_PATTERNS = [
    re.compile(r"(?i)\.min\.(?:js|css)$"),
    re.compile(r"(?i)\.bundle\.(?:js|css)$"),
    re.compile(r"(?i)\.(?:generated|gen)\.[a-z0-9]+$"),
    re.compile(r"(?i)_pb2(?:_grpc)?\.py$"),
    re.compile(r"(?i)\.pb\.go$"),
    re.compile(r"(?i)\.map$"),
    re.compile(r"(?i)^(?:package-lock\.json|yarn\.lock|pnpm-lock\.yaml|poetry\.lock|Pipfile\.lock)$"),
]

_GENERATED_CONTENT_MARKERS = [
    "@generated",
    "do not edit",
    "generated by",
    "auto-generated",
    "automatically generated",
    "this file is generated by",
    "code generated by",
]

_TEST_SEGMENTS = {"test", "tests", "__tests__", "__test__", "spec", "specs"}
_TEST_SUFFIXES = (
    "_test.py", "_spec.py", "test.py",
    ".test.ts", ".test.js", ".test.tsx", ".test.jsx",
    ".spec.ts", ".spec.js", ".spec.tsx", ".spec.jsx",
)

_CONFIG_FILENAMES = {
    ".codeatlas.yml", ".codeatlas.yaml",
    "pyproject.toml", "setup.cfg", "setup.py",
    "package.json", "tsconfig.json", "jsconfig.json",
    "pytest.ini", "tox.ini", ".editorconfig", ".gitignore",
    "makefile", "dockerfile", "cargo.toml", "go.mod", "go.sum",
}

_CONFIG_PATTERNS = [
    re.compile(r"(?i)^tsconfig(?:\.[^/]+)?\.json$"),
    re.compile(r"(?i)^\.eslintrc(?:\.[^/]+)?$"),
    re.compile(r"(?i)^\.prettierrc(?:\.[^/]+)?$"),
    re.compile(r"(?i)^(?:webpack|vite|rollup|babel|jest|vitest|next)\.config\.[a-z0-9]+$"),
    re.compile(r"(?i)^docker-compose(?:-[^/]+)?\.ya?ml$"),
    re.compile(r"(?i)^requirements(?:-[^/]+)?\.txt$"),
]


def is_binary_file(full_path: Path) -> bool:
    """Check if file is binary by extension or null byte presence."""
    if full_path.suffix.lower() in _BINARY_EXTENSIONS:
        return True
    try:
        with full_path.open("rb") as f:
            chunk = f.read(8192)
            if b"\x00" in chunk:
                return True
    except OSError:
        return False
    return False


def is_generated_file(rel_path: str, content: str | None = None) -> bool:
    """Detect if a file is generated from its name or top contents."""
    norm = rel_path.replace("\\", "/")
    filename = norm.rsplit("/", 1)[-1]
    for pattern in _GENERATED_PATTERNS:
        if pattern.search(filename):
            return True
    if content:
        head = content[:2000].lower()
        for marker in _GENERATED_CONTENT_MARKERS:
            if marker in head:
                return True
    return False


def is_test_file(rel_path: str) -> bool:
    """Detect if a file is a test or spec file."""
    norm = rel_path.replace("\\", "/").lower()
    parts = norm.split("/")
    filename = parts[-1]

    # Check directory segment
    if any(segment in _TEST_SEGMENTS for segment in parts[:-1]):
        return True

    # Check prefix or suffix
    if filename.startswith("test_") or filename.startswith("test-"):
        return True
    if any(filename.endswith(sfx) for sfx in _TEST_SUFFIXES):
        return True
    return False


def is_configuration_file(rel_path: str) -> bool:
    """Detect if a file is a configuration or dependency manifest."""
    norm = rel_path.replace("\\", "/").lower()
    filename = norm.rsplit("/", 1)[-1]

    if norm.startswith(".github/") or "/.github/" in norm:
        return True
    if filename in _CONFIG_FILENAMES:
        return True
    for pattern in _CONFIG_PATTERNS:
        if pattern.search(filename):
            return True
    return False


def classify_file(
    repo_root: Path,
    rel_path: str,
    *,
    max_bytes: int = 1_000_000,
) -> RepositoryFile:
    """Build a RepositoryFile metadata record for a repository path."""
    norm_path = rel_path.replace("\\", "/")
    full_path = repo_root / norm_path

    try:
        stat = full_path.stat()
        file_bytes = stat.st_size
    except OSError:
        file_bytes = 0

    binary = is_binary_file(full_path)
    lang = detect_language(norm_path).value

    content: str | None = None
    line_count = 0
    if not binary and file_bytes <= max_bytes:
        try:
            content = full_path.read_text(encoding="utf-8", errors="replace")
            line_count = len(content.splitlines()) if content else 0
        except OSError:
            content = None

    test = is_test_file(norm_path)
    config = is_configuration_file(norm_path)
    generated = is_generated_file(norm_path, content)

    # Determine kind
    if test:
        file_kind = "test"
    elif config:
        file_kind = "configuration"
    elif lang in {"python", "typescript", "javascript", "java", "go", "rust"}:
        file_kind = "source"
    elif norm_path.lower().endswith((".md", ".rst", ".txt", ".adoc")):
        file_kind = "documentation"
    elif norm_path.lower().endswith((".sh", ".bash", ".ps1", ".bat", ".cmd")):
        file_kind = "build"
    elif binary:
        file_kind = "asset"
    else:
        file_kind = "other"

    if binary:
        parse_status = "skipped"
    elif file_bytes > max_bytes:
        parse_status = "skipped"
    elif lang in {"python", "typescript", "javascript"}:
        parse_status = "unsupported"  # will be updated to 'parsed' or 'failed' by parser
    else:
        parse_status = "unsupported"

    return RepositoryFile(
        path=norm_path,
        language=lang,
        file_kind=file_kind,
        bytes=file_bytes,
        line_count=line_count,
        is_test=test,
        is_generated=generated,
        is_configuration=config,
        is_binary=binary,
        parse_status=parse_status,
    )


__all__ = [
    "is_binary_file",
    "is_generated_file",
    "is_test_file",
    "is_configuration_file",
    "classify_file",
]
