"""Comprehensive unit tests for repository intelligence and symbol context."""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest
from typer.testing import CliRunner

from codeatlas.cli import app
from codeatlas.git.models import ChangeStatus, Diff, FileChange, LineRange
from codeatlas.repository import (
    ContextCandidate,
    DependencyGraph,
    ImportReference,
    IndexDiagnostic,
    RepositoryFile,
    RepositoryIndex,
    Symbol,
    SymbolReference,
    build_repository_index,
    classify_file,
    deserialize_index_from_json,
    extract_python_imports,
    extract_python_symbols,
    extract_references_for_file,
    extract_ts_js_imports,
    extract_ts_js_symbols,
    identify_changed_symbols,
    is_binary_file,
    is_configuration_file,
    is_generated_file,
    is_index_fresh,
    is_test_file,
    make_symbol_id,
    resolve_import_path,
    retrieve_context,
    scan_repository,
    serialize_index_to_json,
)
from codeatlas.orchestrator import run_review

runner = CliRunner()


def _git(cwd: Path, *args: str) -> None:
    subprocess.run(["git", *args], cwd=cwd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)


# 1. File inventory tests
def test_file_inventory(tmp_path: Path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "main.py").write_text("def hello(): pass\n", encoding="utf-8")
    inventory = scan_repository(tmp_path)
    assert "src/main.py" in inventory
    file_item = inventory["src/main.py"]
    assert file_item.path == "src/main.py"
    assert file_item.language == "python"
    assert file_item.file_kind == "source"
    assert file_item.line_count == 1
    assert not file_item.is_binary
    assert not file_item.is_test


# 2. Exclusion tests
def test_exclusions_default_and_custom(tmp_path: Path):
    (tmp_path / "node_modules" / "pkg").mkdir(parents=True)
    (tmp_path / "node_modules" / "pkg" / "index.js").write_text("module.exports = {};", encoding="utf-8")
    (tmp_path / "dist").mkdir()
    (tmp_path / "dist" / "bundle.js").write_text("var x = 1;", encoding="utf-8")
    (tmp_path / "custom_ignored").mkdir()
    (tmp_path / "custom_ignored" / "temp.txt").write_text("skip", encoding="utf-8")
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "app.py").write_text("print(1)", encoding="utf-8")

    inventory = scan_repository(tmp_path, exclude_paths=["custom_ignored/**"])
    assert "src/app.py" in inventory
    assert "node_modules/pkg/index.js" not in inventory
    assert "dist/bundle.js" not in inventory
    assert "custom_ignored/temp.txt" not in inventory


# 3. Binary-file tests
def test_binary_file_detection(tmp_path: Path):
    bin_file = tmp_path / "image.png"
    bin_file.write_bytes(b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR")
    data_bin = tmp_path / "data.bin"
    data_bin.write_bytes(b"hello\x00world")
    text_file = tmp_path / "readme.txt"
    text_file.write_text("clean text", encoding="utf-8")

    assert is_binary_file(bin_file)
    assert is_binary_file(data_bin)
    assert not is_binary_file(text_file)

    rep_file = classify_file(tmp_path, "image.png")
    assert rep_file.is_binary
    assert rep_file.parse_status == "skipped"


# 4. Generated-file detection tests
def test_generated_file_detection(tmp_path: Path):
    assert is_generated_file("bundle.min.js")
    assert is_generated_file("package-lock.json")
    assert is_generated_file("service_pb2.py")
    assert is_generated_file("types.generated.ts")
    content = "// @generated by protobuf generator\n// DO NOT EDIT\n"
    assert is_generated_file("src/client.ts", content=content)
    assert not is_generated_file("src/client.ts", content="// Regular handwritten file\n")


# 5. Test-file detection tests
def test_test_file_detection():
    assert is_test_file("tests/unit/test_auth.py")
    assert is_test_file("src/components/__tests__/button.test.tsx")
    assert is_test_file("src/service.spec.ts")
    assert is_test_file("test_utils.py")
    assert not is_test_file("src/components/button.tsx")
    assert not is_test_file("src/testing_helpers/mock.py")  # helper, not direct test filename


# 6. Python import extraction
def test_python_import_extraction():
    source = """
import os
import sys as system
from pathlib import Path, PurePath
from .local_mod import helper as h
from ..parent_mod import parent_func
"""
    imports, diags = extract_python_imports("src/app.py", source)
    assert not diags
    modules = {imp.module: imp for imp in imports}
    assert "os" in modules
    assert "sys" in modules and modules["sys"].alias == "system"
    assert "pathlib" in modules and set(modules["pathlib"].names) == {"Path", "PurePath"}
    assert ".local_mod" in modules and modules[".local_mod"].is_relative
    assert "..parent_mod" in modules and modules["..parent_mod"].is_relative


# 7. TypeScript import extraction
def test_typescript_import_extraction():
    source = """
import defaultExport from "./service";
import { getSession, refreshSession as refresh } from "./auth";
import * as utils from "../utils";
import "normalize.css";
export { helper } from "./helper";
const config = require("./config.json");
"""
    imports, diags = extract_ts_js_imports("src/index.ts", source)
    assert not diags
    mod_map = {imp.module: imp for imp in imports}
    assert "./service" in mod_map and "defaultExport" in mod_map["./service"].names
    assert "./auth" in mod_map and "getSession" in mod_map["./auth"].names
    assert "../utils" in mod_map and "utils" in mod_map["../utils"].names
    assert "normalize.css" in mod_map
    assert "./helper" in mod_map and "helper" in mod_map["./helper"].names
    assert "./config.json" in mod_map and "config" in mod_map["./config.json"].names


# 8. Dynamic-import handling
def test_dynamic_import_handling():
    source = """
const mod = await import("./dynamic-module");
const dynVar = await import(dynamicPath);
const rDyn = require(runtimeVar);
"""
    imports, diags = extract_ts_js_imports("src/loader.ts", source)
    dynamic_imports = [imp for imp in imports if imp.is_dynamic]
    assert len(dynamic_imports) == 3
    assert any(imp.module == "./dynamic-module" for imp in dynamic_imports)
    assert any(imp.module == "<dynamic>" for imp in dynamic_imports)
    assert any(d.reason == "dynamic_import" for d in diags)


# 9. Python symbol extraction
def test_python_symbol_extraction():
    source = """
TOP_LEVEL = 42

def calculate_hash(data: str) -> str:
    return data

async def fetch_user(uid: str):
    pass

class UserManager:
    def __init__(self):
        pass

    async def get_user(self, uid: str):
        pass
"""
    symbols, diags = extract_python_symbols("src/user.py", source)
    assert not diags
    names = {s.name: s for s in symbols}
    assert "TOP_LEVEL" in names and names["TOP_LEVEL"].kind == "module_variable"
    assert "calculate_hash" in names and names["calculate_hash"].kind == "function"
    assert "fetch_user" in names and names["fetch_user"].kind == "async_function"
    assert "UserManager" in names and names["UserManager"].kind == "class"
    assert "get_user" in names and names["get_user"].kind == "method"
    assert names["get_user"].parent_id == names["UserManager"].id


# 10. TypeScript symbol extraction
def test_typescript_symbol_extraction():
    source = """
export interface UserProfile {
  id: string;
  name: string;
}

export type Token = string;

export function getSession(token: Token): UserProfile {
  return { id: "1", name: "admin" };
}

export const validateToken = async (token: string) => {
  return true;
};

export class AuthService {
  public async login(creds: any): Promise<boolean> {
    return true;
  }
}
"""
    symbols, diags = extract_ts_js_symbols("src/auth.ts", source)
    assert not diags
    names = {s.name: s for s in symbols}
    assert "UserProfile" in names and names["UserProfile"].kind == "interface"
    assert "Token" in names and names["Token"].kind == "type_alias"
    assert "getSession" in names and names["getSession"].kind == "function"
    assert "validateToken" in names and names["validateToken"].kind == "function"
    assert "AuthService" in names and names["AuthService"].kind == "class"
    assert "login" in names and names["login"].kind == "method"
    assert names["login"].parent_id == names["AuthService"].id


# 11. Changed-symbol mapping
def test_changed_symbol_mapping():
    sym1 = Symbol(
        id="sym::src/auth.py::function::root::login",
        file="src/auth.py",
        name="login",
        kind="function",
        start_line=10,
        end_line=25,
    )
    sym2 = Symbol(
        id="sym::src/auth.py::function::root::logout",
        file="src/auth.py",
        name="logout",
        kind="function",
        start_line=30,
        end_line=45,
    )
    index = RepositoryIndex(
        files={"src/auth.py": RepositoryFile(path="src/auth.py", bytes=100, line_count=50)},
        symbols=[sym1, sym2],
    )
    diff = Diff(
        "base",
        "head",
        files=(
            FileChange(
                path="src/auth.py",
                status=ChangeStatus.MODIFIED,
                new_ranges=(LineRange(start=15, count=3),),
            ),
        ),
    )

    changed = identify_changed_symbols(index, diff)
    assert len(changed) == 1
    assert changed[0].name == "login"


# 12. Same-file reference mapping
def test_same_file_reference_mapping():
    source = """
def helper():
    return 1

def main():
    return helper()
"""
    symbols, _ = extract_python_symbols("app.py", source)
    refs = extract_references_for_file(
        "app.py",
        source,
        symbols,
        file_imports=[],
        all_symbols_by_file={"app.py": symbols},
    )
    helper_ref = next((r for r in refs if r.symbol_name == "helper"), None)
    assert helper_ref is not None
    assert helper_ref.resolution_reason == "same_file_definition"
    assert helper_ref.resolved_symbol_id == "sym::app.py::function::root::helper"


# 13. Local import resolution
def test_local_import_resolution():
    available = {"src/auth.ts", "src/utils/index.ts", "src/models/user.py"}
    assert resolve_import_path("src/app.ts", "./auth", available) == "src/auth.ts"
    assert resolve_import_path("src/app.ts", "./utils", available) == "src/utils/index.ts"
    assert resolve_import_path("src/main.py", ".models.user", available) == "src/models/user.py"
    assert resolve_import_path("src/app.ts", "lodash", available) is None


# 14. Unresolved-reference diagnostics
def test_unresolved_reference_diagnostics():
    source = """
from unknown_package import externalLib

def run():
    externalLib()
    unknownFunction()
"""
    symbols, _ = extract_python_symbols("app.py", source)
    imports, _ = extract_python_imports("app.py", source)
    refs = extract_references_for_file(
        "app.py",
        source,
        symbols,
        imports,
        all_symbols_by_file={"app.py": symbols},
    )
    ext_ref = next((r for r in refs if r.symbol_name == "externalLib"), None)
    unk_ref = next((r for r in refs if r.symbol_name == "unknownFunction"), None)
    assert ext_ref is not None and ext_ref.unresolved_reason == "external_package"
    assert unk_ref is not None and unk_ref.unresolved_reason == "ambiguous_name"


# 15. Stable symbol-ID tests
def test_stable_symbol_id():
    id1 = make_symbol_id("src/auth/service.ts", "function", None, "getSession")
    id2 = make_symbol_id("src\\auth\\service.ts", "function", None, "getSession")
    assert id1 == id2 == "sym::src/auth/service.ts::function::root::getSession"
    assert "token" not in id1.lower()
    assert "-" not in id1.split("::")[-1]


# 16. Stable index serialization tests
def test_stable_index_serialization(tmp_path: Path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "calc.py").write_text("def add(a, b): return a + b\n", encoding="utf-8")
    index = build_repository_index(tmp_path, commit_sha="abc1234")
    serialized = serialize_index_to_json(index)
    restored = deserialize_index_from_json(serialized)

    assert restored.index_version == index.index_version
    assert restored.commit_sha == "abc1234"
    assert len(restored.files) == len(index.files)
    assert len(restored.symbols) == len(index.symbols)
    assert restored.symbols[0].id == index.symbols[0].id


# 17. Context ranking tests
def test_context_ranking():
    sym = Symbol(
        id="sym::src/core.py::function::root::run",
        file="src/core.py",
        name="run",
        kind="function",
        start_line=5,
        end_line=15,
    )
    ref = SymbolReference(
        file="tests/test_core.py",
        symbol_name="run",
        line=10,
        resolved_symbol_id=sym.id,
    )
    index = RepositoryIndex(
        files={
            "src/core.py": RepositoryFile(path="src/core.py", bytes=200, line_count=20),
            "tests/test_core.py": RepositoryFile(path="tests/test_core.py", bytes=150, line_count=25, is_test=True),
        },
        symbols=[sym],
        references=[ref],
    )
    candidates = retrieve_context(index, changed_files=["src/core.py"], changed_symbols=[sym])
    assert len(candidates) >= 2
    assert candidates[0].score > candidates[1].score
    assert candidates[0].signals == ["changed_symbol"]
    assert candidates[1].signals == ["test_reference"]


# 18. Retrieval reason tests
def test_retrieval_reasons():
    sym = Symbol(
        id="sym::src/service.ts::function::root::fetch",
        file="src/service.ts",
        name="fetch",
        kind="function",
        start_line=1,
        end_line=10,
    )
    index = RepositoryIndex(
        files={"src/service.ts": RepositoryFile(path="src/service.ts", bytes=100, line_count=10)},
        symbols=[sym],
    )
    candidates = retrieve_context(index, changed_files=["src/service.ts"], changed_symbols=[sym])
    for cand in candidates:
        assert isinstance(cand.reason, str) and len(cand.reason) > 0
        assert len(cand.signals) > 0
        assert 0.0 <= cand.score <= 1.0


# 19. Index freshness tests
def test_index_freshness():
    index = RepositoryIndex(commit_sha="commit-12345")
    assert is_index_fresh(index, "commit-12345")
    assert not is_index_fresh(index, "commit-99999")
    assert not is_index_fresh(index, None)


# 20. Manifest integration tests
def test_manifest_integration(tmp_path: Path):
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "eval@example.invalid")
    _git(tmp_path, "config", "user.name", "eval")
    (tmp_path / "hello.py").write_text("def greet(): return 'hi'\n", encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "initial")
    (tmp_path / "hello.py").write_text("def greet(): return 'hello world'\n", encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "updated")

    result = run_review(tmp_path, "HEAD~1", "HEAD", index_repository=True)
    manifest = result.manifest
    assert manifest.index_version == "1.0.0"
    assert manifest.indexed_files >= 1
    assert manifest.indexed_symbols >= 1
    assert len(manifest.changed_symbols) >= 1
    assert len(manifest.context_candidates) >= 1


# 21. CLI context-output tests
def test_cli_context_output(tmp_path: Path):
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "eval@example.invalid")
    _git(tmp_path, "config", "user.name", "eval")
    (tmp_path / "app.py").write_text("def start(): pass\n", encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "initial")
    (tmp_path / "app.py").write_text("def start(): print('started')\n", encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "updated")

    context_json = tmp_path / "context.json"
    cmd_result = runner.invoke(
        app,
        [
            "review",
            "--repo", str(tmp_path),
            "--base", "HEAD~1",
            "--head", "HEAD",
            "--index-repository",
            "--context-output", str(context_json),
        ],
    )
    assert cmd_result.exit_code == 0
    assert context_json.is_file()
    data = json.loads(context_json.read_text(encoding="utf-8"))
    assert isinstance(data, list)
    assert len(data) > 0
    assert "signals" in data[0]


# 22. Malformed-source resilience tests
def test_malformed_source_resilience(tmp_path: Path):
    (tmp_path / "broken.py").write_text("def bad_syntax(: pass\n", encoding="utf-8")
    index = build_repository_index(tmp_path)
    assert "broken.py" in index.files
    assert index.files["broken.py"].parse_status == "failed"
    assert any(d.reason == "syntax_error" for d in index.diagnostics)


# 23. Redaction/logging tests
def test_redaction_and_logging(tmp_path: Path):
    (tmp_path / "secret.py").write_text("API_KEY = 'AKIA1234567890EXAMPLE'\n", encoding="utf-8")
    index = build_repository_index(tmp_path)
    index_json = serialize_index_to_json(index)
    assert "AKIA1234567890EXAMPLE" not in index_json


# 24. Original repository unchanged test
def test_original_repository_unchanged(tmp_path: Path):
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "eval@example.invalid")
    _git(tmp_path, "config", "user.name", "eval")
    file_path = tmp_path / "data.py"
    file_path.write_text("DATA = 123\n", encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "initial")

    file_path.write_text("DATA = 456\n", encoding="utf-8")
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-qm", "head")

    before_content = file_path.read_text(encoding="utf-8")
    run_review(tmp_path, "HEAD~1", "HEAD", index_repository=True)
    after_content = file_path.read_text(encoding="utf-8")

    assert before_content == after_content


# 25. No repository-code-execution test
def test_no_repository_code_execution(tmp_path: Path):
    sentinel = tmp_path / "SENTINEL.txt"
    evil_code = f"""
import os
with open('{str(sentinel).replace('\\', '/')}', 'w') as f:
    f.write('EXECUTED')
"""
    (tmp_path / "malicious.py").write_text(evil_code, encoding="utf-8")
    build_repository_index(tmp_path)
    assert not sentinel.exists(), "Repository code was executed during indexing!"


def test_manifest_schema_validation():
    """Verify that manifests with and without repository index validate against JSON schema."""
    import jsonschema
    from codeatlas.orchestrator.manifest import RunManifest

    schema_path = Path(__file__).resolve().parents[2] / "schemas" / "run-manifest.schema.json"
    schema = json.loads(schema_path.read_text(encoding="utf-8"))

    m1 = RunManifest(run_id="run-1", repository="repo", base_ref="main", head_ref="HEAD")
    jsonschema.validate(m1.model_dump(mode="json"), schema)

    m2 = RunManifest(
        run_id="run-2",
        repository="repo",
        base_ref="main",
        head_ref="HEAD",
        index_version="1.0.0",
        indexed_files=5,
        indexed_symbols=10,
        indexed_imports=3,
        changed_symbols=[{"id": "sym::1", "file": "a.py"}],
        context_candidates=[{"file": "b.py", "reason": "test"}],
        index_duration_ms=10.5,
        retrieval_duration_ms=1.2,
    )
    jsonschema.validate(m2.model_dump(mode="json"), schema)
